root: true
extends:
  - prettier
  - plugin:react/recommended
parser: "@babel/eslint-parser"
settings:
  react:
    version: "16.8"
env:
  browser: true
  es6: true
  node: true
globals:
  __PATH_PREFIX__: true
rules:
  no-useless-escape: 0
  prefer-const: 2
  no-unused-vars:
    - 2
    -
      argsIgnorePattern: ^_
      varsIgnorePattern: ^_
  react/display-name: 0
